version: '3.3'
services:
  bytepay:
    image: nginx
    volumes:
      - .:/app
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
      - /root/workspace/laf/deploy-scripts/cert:/cert
    ports:
      - "80:80"
      - "443:443"